name: Build

on:
  workflow_dispatch:
#  push:
#    branches: [ "main", "master" ]
#  pull_request:
#    branches: [ "main", "master" ]

jobs:
  build:
    strategy:
      matrix:
        include:
#          - os: windows-latest
#            platform: win-x64
#          - os: macos-latest
#            platform: osx-x64
          - os: macos-latest
            platform: osx-arm64
            
    runs-on: ${{ matrix.os }}
    
    env:
      Solution_Name: DoViMuxer.sln
      Project_Path: DoViMuxer/DoViMuxer.csproj
      
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      
    - name: 设置 .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: 安装 UPX 工具 (仅 macOS)
      if: runner.os == 'macOS'
      run: |
        brew install upx
        which upx

    - name: 还原依赖
      run: dotnet restore ${{ env.Solution_Name }}
      
    - name: 构建项目
      run: |
        dotnet build ${{ env.Solution_Name }} -c Release --no-restore
        
    - name: 发布单体文件
      run: |
        dotnet publish ${{ env.Project_Path }} -c Release -r ${{ matrix.platform }} --self-contained true -o ./publish/${{ matrix.platform }}
        
    - name: 设置可执行权限 (仅 macOS)
      if: runner.os == 'macOS'
      run: |
        chmod +x ./publish/${{ matrix.platform }}/DoViMuxer

    - name: 上传构建产物
      uses: actions/upload-artifact@v3
      with:
        name: DoViMuxer-${{ matrix.platform }}
        path: ./publish/${{ matrix.platform }}/*