name: Build

on:
  workflow_dispatch:
#  push:
#    branches: [ "main", "master" ]
#  pull_request:
#    branches: [ "main", "master" ]

jobs:
  build:
    strategy:
      matrix:
        include:
#          - os: windows-latest
#            platform: win-x64
#          - os: windows-latest
#            platform: win-arm64
#          - os: ubuntu-latest
#            platform: linux-x64
#          - os: ubuntu-latest
#            platform: linux-arm64
#          - os: macos-latest
#            platform: osx-x64
          - os: macos-latest
            platform: osx-arm64
            
    runs-on: ${{ matrix.os }}
    
    env:
      Project_Path: DoViMuxer/DoViMuxer.csproj
      
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置 .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: 还原依赖
      run: dotnet restore ${{ env.Project_Path }}
      
    - name: 构建项目
      run: |
        dotnet publish ${{ env.Project_Path }} \
          -c Release \
          -r ${{ matrix.platform }} \
          --self-contained true \
          -p:PublishSingleFile=true \
          -p:EnableCompressionInSingleFile=true \
          -o ./publish/${{ matrix.platform }}
        
    - name: 设置可执行权限 (Unix)
      if: runner.os != 'Windows'
      run: chmod +x ./publish/${{ matrix.platform }}/DoViMuxer
        
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: DoViMuxer-${{ matrix.platform }}
        path: ./publish/${{ matrix.platform }}/*
        compression-level: 0