name: Build Latest

on:
  workflow_dispatch:
    inputs:
      doRelease:
        description: 'Publish new release'
        type: boolean
        default: false
        required: false
      tag:
        type: string
        description: 'Release version tag (e.g. v1.2.3)'
        required: true
      ref:
        type: string
        description: 'Git ref from which to release'
        required: true
        default: 'main'

env:
  DOTNET_SDK_VERSION: "8.0.*"

jobs:
  build-mac-x64-arm64:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
      - run: dotnet publish DoViMuxer -r osx-arm64 -c Release -o artifact-arm64
      - run: dotnet publish DoViMuxer -r osx-x64 -c Release -o artifact-x64

      - name: Upload Artifact[osx-x64]
        uses: actions/upload-artifact@v3.1.3
        with:
          name: DoViMuxer_Beta_osx-x64
          path: artifact-x64/DoViMuxer
      - name: Upload Artifact[osx-arm64]
        uses: actions/upload-artifact@v3.1.3
        with:
          name: DoViMuxer_Beta_osx-arm64
          path: artifact-arm64/DoViMuxer